apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "justmount.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "justmount.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "justmount.fullname" . }}
    spec:
      serviceAccountName: {{ include "justmount.serviceAccountName" . }}
      hostNetwork: {{ .Values.node.hostNetwork }}
      containers:
        - name: node-driver-registrar
          image: {{ .Values.registrar.image }}
          args:
            - --v={{ .Values.registrar.logLevel }}
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.node.kubeletDir }}/plugins/{{ .Values.csidriver.name }}/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: justmount
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --node-endpoint={{ .Values.node.endpoint }}
            - --node-id=$({{ .Values.node.nodeIDEnv }})
          env:
            - name: {{ .Values.node.nodeIDEnv }}
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: {{ .Values.node.privileged }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: {{ .Values.node.kubeletDir }}
              mountPropagation: Bidirectional
            - name: fuse-dev
              mountPath: {{ .Values.node.fuseDevice }}
      volumes:
        - name: plugin-dir
          hostPath:
            path: {{ .Values.node.kubeletDir }}/plugins/{{ .Values.csidriver.name }}
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.node.kubeletDir }}/plugins_registry
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.node.kubeletDir }}
            type: Directory
        - name: fuse-dev
          hostPath:
            path: {{ .Values.node.fuseDevice }}
            type: CharDevice
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
